services:
  - type: web
    name: backend-sql
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tu-base
          property: connectionString
